### ISSUE TITLE
TU Delft 2015 Cover template enhancement

### ISSUE THREAD

**Issue by evetion** [tudelftgeomatics/thesis_template#3]
Recently the [huisstijl](https://intranet.tudelft.nl/services/communicatie/communicatie-directie-communication/handleidingen/huisstijl-tu-delft/downloads/) of the TU Delft has changed. The cover now looks much more modern and could be integrated with this template.

Example is found [here](https://intranet.tudelft.nl/fileadmin/Files/medewerkersportal/mc/huisstijl/Downloads/latex_report.pdf), its source can be downloaded from [here](https://intranet.tudelft.nl/fileadmin/Files/medewerkersportal/mc/huisstijl/Downloads/latex_newreport.zip)

As of yet though, the source is a mess and does seem to produce very odd results with long titles or subtitles.

**Comment by hugoledoux** [comment]
tried it a while ago: indeed the code is a bit of a joke... I'll leave the cover page to the creativity of people I think, or just use Illustrator and then \includepdf{cover.pdf}.
